# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
    #- name: Projects
    #  url: projects/
    #  weight: 30
    #- name: Teaching
    #  url: teaching/
    #  weight: 40


# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: ru
  contentDir: content/ru
  title: Николаев Дмитрий
  params:
    # Site header
    header:
      navbar:
        enable: true
        blox: "navbar"
        fixed_to_top: true
        show_search: true
        show_theme_chooser: true
        logo:
          text: "Николаев Дмитрий"

    # Site footer
    footer:
      copyright:
        notice: '© {year} Me. This work is licensed under {license}'
        license:
          enable: true
          allow_derivatives: false
          share_alike: true
          allow_commercial: false

    # Localization
    locale:
      date_format: 'Jan 2, 2006'
      time_format: '3:04 PM'
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
